### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by Podolyan98** [dolthub/doltlab-issues#100]
# Bug report

### Description

I deployed Doltlab then went to http://localhost and got an error:

```bash
Application error: a client-side exception has occurred (see the browser console for more information).
```

### Environment

Doltlab: v2.1.1
Docker: 27.3.1, build ce12230
Docker Compose: v2.29.7

installer_config.yaml:

```bash
host: "localhost"

services:
  doltlabdb:
    admin_password: "12345"
    dolthubapi_password: "12345"
default_user:
  name: "admin"
  password: "12345"
  email: "admin@localhost"
```

### Relevant logs

doltlabgraphql:

```bash
doltlabgraphql-1  | > @dolthub/graphql-server@0.1.0 start
doltlabgraphql-1  | > nest start
doltlabgraphql-1  |
doltlabgraphql-1  | [Nest] 25  - 12/16/2024, 8:16:03 PM     LOG [NestFactory] Starting Nest application...
doltlabgraphql-1  | [Nest] 25  - 12/16/2024, 8:16:03 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +72ms
doltlabgraphql-1  | [Nest] 25  - 12/16/2024, 8:16:03 PM     LOG [InstanceLoader] TerminusModule dependencies initialized +4ms
doltlabgraphql-1  | [Nest] 25  - 12/16/2024, 8:16:03 PM     LOG [InstanceLoader] CacheModule dependencies initialized +0ms
doltlabgraphql-1  | [Nest] 25  - 12/16/2024, 8:16:03 PM     LOG [InstanceLoader] GithubStarModule dependencies initialized +1ms
doltlabgraphql-1  | [Nest] 25  - 12/16/2024, 8:16:03 PM     LOG [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +2ms
doltlabgraphql-1  | [Nest] 25  - 12/16/2024, 8:16:03 PM     LOG [InstanceLoader] GraphQLModule dependencies initialized +1ms
doltlabgraphql-1  | [Nest] 25  - 12/16/2024, 8:16:03 PM     LOG [InstanceLoader] AppModule dependencies initialized +1ms
doltlabgraphql-1  | [Nest] 25  - 12/16/2024, 8:16:03 PM     LOG [RoutesResolver] HealthController {/health}: +13ms
doltlabgraphql-1  | [Nest] 25  - 12/16/2024, 8:16:03 PM     LOG [RouterExplorer] Mapped {/health, GET} route +6ms
doltlabgraphql-1  | [Nest] 25  - 12/16/2024, 8:16:03 PM     LOG [GraphQLModule] Mapped {/graphql, POST} route +475ms
doltlabgraphql-1  | [Nest] 25  - 12/16/2024, 8:16:03 PM     LOG [NestApplication] Nest application successfully started +3ms
doltlabgraphql-1  | [Nest] 25  - 12/16/2024, 8:16:32 PM   ERROR [ExceptionsHandler] no healthy upstream
doltlabgraphql-1  | Error: no healthy upstream
doltlabgraphql-1  |     at Object.onEnd (/usr/web/packages/ld-proto/ld/services/dolthubapi/v1alpha1/doltlab_info_pb_service.js:122:21)
doltlabgraphql-1  |     at /usr/web/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24233
doltlabgraphql-1  |     at /usr/web/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11490
doltlabgraphql-1  |     at Array.forEach (<anonymous>)
doltlabgraphql-1  |     at e.rawOnError (/usr/web/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11452)
doltlabgraphql-1  |     at e.onTransportHeaders (/usr/web/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:9025)
doltlabgraphql-1  |     at NodeHttp.NodeHttp.responseCallback (/usr/web/node_modules/@improbable-eng/grpc-web-node-http-transport/src/index.ts:36:18)
doltlabgraphql-1  |     at Object.onceWrapper (node:events:632:26)
doltlabgraphql-1  |     at ClientRequest.emit (node:events:517:28)
doltlabgraphql-1  |     at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
```

doltlabui:

```bash
doltlabui-1  |  ⨯ ApolloError: no healthy upstream
doltlabui-1  |     at new ApolloError (/usr/web/node_modules/@apollo/client/errors/errors.cjs:33:28)
doltlabui-1  |     at /usr/web/node_modules/@apollo/client/core/core.cjs:1996:47
doltlabui-1  |     at both (/usr/web/node_modules/@apollo/client/utilities/utilities.cjs:1353:31)
doltlabui-1  |     at /usr/web/node_modules/@apollo/client/utilities/utilities.cjs:1344:72
doltlabui-1  |     at new Promise (<anonymous>)
doltlabui-1  |     at Object.then (/usr/web/node_modules/@apollo/client/utilities/utilities.cjs:1344:24)
doltlabui-1  |     at Object.next (/usr/web/node_modules/@apollo/client/utilities/utilities.cjs:1355:49)
doltlabui-1  |     at notifySubscription (/usr/web/node_modules/zen-observable/lib/Observable.js:135:18)
doltlabui-1  |     at onNotify (/usr/web/node_modules/zen-observable/lib/Observable.js:179:3)
doltlabui-1  |     at SubscriptionObserver.next (/usr/web/node_modules/zen-observable/lib/Observable.js:235:7) {
doltlabui-1  |   graphQLErrors: [
doltlabui-1  |     {
doltlabui-1  |       message: 'no healthy upstream',
doltlabui-1  |       locations: [Array],
doltlabui-1  |       path: [Array],
doltlabui-1  |       extensions: [Object]
doltlabui-1  |     }
doltlabui-1  |   ],
doltlabui-1  |   protocolErrors: [],
doltlabui-1  |   clientErrors: [],
doltlabui-1  |   networkError: null,
doltlabui-1  |   extraInfo: undefined
doltlabui-1  | }
```

**Comment by timsehn** [comment]
Did you follow the Getting Started guide?

https://docs.doltlab.com/introduction/getting-started

Dustin may have a better idea of what is going on.

**Comment by coffeegoddd** [comment]
@Podolyan98 thanks for the report. DoltLab cannot run with host `localhost`, since DoltLab is a Docker Compose application, which does not resolve `localhost` and there's some bespoke hostname handling within DoltLab itself that also does not allow for `localhost` . 

Instead, you should use the IP address of the host machine or a dns name that resolves to the host machine, and ensure it's reachable on the public internet. I would suggest downloading and running the latest DoltLab version, [v2.3.3](https://github.com/dolthub/doltlab-issues/releases/tag/v2.3.3), and following the getting started guide here https://docs.doltlab.com/introduction/getting-started

But if you hit any issues other issues, let us know, we're happy to help you get going.

**Comment by Podolyan98** [comment]
@coffeegoddd I tried using `10.50.0.18`. The same error occurred.

**Comment by coffeegoddd** [comment]
@Podolyan98 after you changed the `installer_config.yaml`'s `host` to `10.50.0.18`, did you rerun the `installer` to regenerate the DoltLab assets?

If so, and it's still not working, can you send me a copy of `docker-compose.yaml` and the output of this command:
```bash
docker logs doltlab_doltlabapi_1
```

you can send to my email, dustin@dolthub.com

**Comment by Podolyan98** [comment]
@coffeegoddd This is how I changed the `host`:

```bash
sudo ./stop.sh
sudo docker compose down -v
sudo vim installer_config.yaml # localhost -> 10.50.0.18
sudo ./installer
sudo ./start.sh
```

`doltlabapi` logs:

```bash
WARN[0000] The "DOLT_DOLTHUBAPI_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] The "DOLT_DOLTHUBAPI_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] The "DEFAULT_USER_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] The "DOLT_DOLTHUBAPI_PASSWORD" variable is not set. Defaulting to a blank string.
WARN[0000] The "DOLT_ADMIN_PASSWORD" variable is not set. Defaulting to a blank string.
doltlabapi-1  | 2024-12-17T08:34:18.607Z        WARN    server/main.go:830      Generating random whitelist api token because none supplied in DOLTHUBAPI_WHITELIST_API_TOKEN.
doltlabapi-1  | main.getWhitelistTokenFromEnv
doltlabapi-1  |         go/services/dolthubapi/cmd/server/main.go:830
doltlabapi-1  | main.main
doltlabapi-1  |         go/services/dolthubapi/cmd/server/main.go:304
doltlabapi-1  | runtime.main
doltlabapi-1  |         GOROOT/src/runtime/proc.go:271
doltlabapi-1  | 2024-12-17T08:34:37.160Z        INFO    server/main.go:953      Successfully created default user       {"default_user": "admin"}
doltlabapi-1  | 2024-12-17T08:34:37.165Z        FATAL   server/main.go:401      Must supply -emailHost and -emailPort
doltlabapi-1  | main.main
doltlabapi-1  |         go/services/dolthubapi/cmd/server/main.go:401
doltlabapi-1  | runtime.main
doltlabapi-1  |         GOROOT/src/runtime/proc.go:271
```

`doltlabgraphql` logs:

```bash
doltlabgraphql-1  | [Nest] 25  - 12/17/2024, 8:38:19 AM   ERROR [ExceptionsHandler] no healthy upstream
doltlabgraphql-1  | Error: no healthy upstream
doltlabgraphql-1  |     at Object.onEnd (/usr/web/packages/ld-proto/ld/services/dolthubapi/v1alpha1/doltlab_info_pb_service.js:122:21)
doltlabgraphql-1  |     at /usr/web/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24233
doltlabgraphql-1  |     at /usr/web/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11490
doltlabgraphql-1  |     at Array.forEach (<anonymous>)
doltlabgraphql-1  |     at e.rawOnError (/usr/web/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11452)
doltlabgraphql-1  |     at e.onTransportHeaders (/usr/web/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:9025)
doltlabgraphql-1  |     at NodeHttp.NodeHttp.responseCallback (/usr/web/node_modules/@improbable-eng/grpc-web-node-http-transport/src/index.ts:36:18)
doltlabgraphql-1  |     at Object.onceWrapper (node:events:632:26)
doltlabgraphql-1  |     at ClientRequest.emit (node:events:517:28)
doltlabgraphql-1  |     at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
```

`docker-compose.yaml`:

```bash
services:
    doltlabapi:
        depends_on:
            - doltlabdb
            - doltlabenvoy
            - doltlabfileserviceapi
            - doltlabremoteapi
        image: public.ecr.aws/dolthub/doltlab/dolthubapi-server:v2.2.1
        command: |-
            -doltlab
            -outboundInternalServiceEndpointHost doltlabenvoy
            -iterTokenEncKeysFile /iter_token.keys
            -iterTokenDecKeysFile /iter_token.keys
            -processAsyncTasks
            -port 60051
            -defaultUser "admin"
            -defaultUserPassword "${DEFAULT_USER_PASSWORD}"
            -defaultUserEmail "admin@localhost"
            -metricsHost "eventsapi.dolthub.com"
            -migrateUp
            -importJobContainerImage "public.ecr.aws/dolthub/doltlab/file-importer:v2.2.1"
            -mergeJobContainerImage "public.ecr.aws/dolthub/doltlab/pull-merge:v2.2.1"
            -sqlReadJobContainerImage "public.ecr.aws/dolthub/doltlab/query-job:v2.2.1"
            -jobEnvoyHost "doltlabenvoy"
            -dolthubWhitelistAllowAll
            -doltUser dolthubapi
            -doltHost doltlabdb
            -doltPort 3306
            -remoteApiHostNameOverrideKey "10.50.0.18:100"
            -websiteURL "http://10.50.0.18"
            -doltremoteapi.url "10.50.0.18"
            -doltremoteapi.port "50051"
            -doltlabRemoteApiHost "10.50.0.18"
            -doltlabRemoteApiPort "50051"
            -remoteApiHostNameOverrideValue "doltlabremoteapi:100"
            -userImportUploadsFileServiceServerHost "http://doltlabenvoy:4321"
            -fileserviceapiServiceEndpoint "http://doltlabenvoy:4321"
            -userImportUploadsFileServiceBrowserHost "http://10.50.0.18:4321"
        environment:
            BUILD_SCM_REVISION: "doltlabapi-v2.2.1"
            DOLT_DOLTHUBAPI_PASSWORD: "${DOLT_DOLTHUBAPI_PASSWORD}"
            DOLTHUB_METRICS_ENABLED: "true"
            DOLTHUBAPI_PASSWORD: "${DOLT_DOLTHUBAPI_PASSWORD}"
            MAILCHIMP_API_KEY: "does_not_work"
            MAILCHIMP_LIST_ID: "does_not_work"
            STRIPE_API_KEY: "does_not_work"
        networks:
            - default
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/doltlab/doltlabapi/iter_token.keys:/iter_token.keys
    doltlabdb:
        image: public.ecr.aws/dolthub/doltlab/dolt-sql-server:v2.2.1
        command: |-
            -l debug
        environment:
            DOLT_ADMIN_PASSWORD: "${DOLT_ADMIN_PASSWORD}"
            DOLT_DOLTHUBAPI_PASSWORD: "${DOLT_DOLTHUBAPI_PASSWORD}"
        networks:
            - default
        volumes:
            - doltlabdb-dolt-data:/var/lib/dolt
            - doltlabdb-dolt-root:/.dolt
            - doltlabdb-dolt-configs:/etc/dolt
            - doltlabdb-dolt-backups:/backups
    doltlabenvoy:
        image: envoyproxy/envoy:v1.28-latest
        command: |-
            -c /envoy.json
        networks:
            - default
        volumes:
            - /opt/doltlab/envoy.json:/envoy.json
        ports:
            - "100:100"
            - "7770:7770"
            - "2001:2001"
            - "4321:4321"
            - "80:80"
    doltlabfileserviceapi:
        depends_on:
            - doltlabenvoy
        image: public.ecr.aws/dolthub/doltlab/fileserviceapi-server:v2.2.1
        command: |-
            -outboundInternalServiceEndpointHost doltlabenvoy
            -iterTokenEncKeysFile /iter_token.keys
            -iterTokenDecKeysFile /iter_token.keys
            -dir /doltlab-user-uploads
            -doltlab
        environment:
            BUILD_SCM_REVISION: "doltlabfileserviceapi-v2.2.1"
            DOLTHUB_METRICS_ENABLED: "true"
        networks:
            - default
        volumes:
            - /opt/doltlab/doltlabfileserviceapi/iter_token.keys:/iter_token.keys
            - doltlab-user-uploads:/doltlab-user-uploads
    doltlabgraphql:
        depends_on:
            - doltlabdb
            - doltlabenvoy
            - doltlabremoteapi
            - doltlabapi
            - doltlabfileserviceapi
        image: public.ecr.aws/dolthub/doltlab/dolthubapi-graphql-server:v2.2.1
        environment:
            DOLTHUBAPI_URL: "http://doltlabenvoy:9443"
            NODE_ENV: "development"
        networks:
            - default
    doltlabremoteapi:
        depends_on:
            - doltlabdb
            - doltlabenvoy
            - doltlabfileserviceapi
        image: public.ecr.aws/dolthub/doltlab/doltremoteapi-server:v2.2.1
        command: |-
            -http-port "100"
            -outboundInternalServiceEndpointHost doltlabenvoy
            -repoTokenEncKeysFile /iter_token.keys
            -repoTokenDecKeysFile /iter_token.keys
            -dir /doltlab-remote-storage
            -metricsHost eventsapi.dolthub.com
            -doltlab
            -allow-nbf-dolt
            -backingStoreHostNameOverrideKey ":100"
            -backingStoreHostNameOverrideValue "doltlabremoteapi:100"
            -backing-store local
            -http-host ":100"
        environment:
            BUILD_SCM_REVISION: "doltlabremoteapi-v2.2.1"
            DOLTHUB_METRICS_ENABLED: "true"
        networks:
            - default
        volumes:
            - /opt/doltlab/doltlabremoteapi/iter_token.keys:/iter_token.keys
            - doltlab-remote-storage:/doltlab-remote-storage
        ports:
            - "50051:50051"
    doltlabui:
        depends_on:
            - doltlabdb
            - doltlabenvoy
            - doltlabfileserviceapi
            - doltlabremoteapi
            - doltlabapi
            - doltlabgraphql
        image: public.ecr.aws/dolthub/doltlab/dolthub-server:v2.2.1
        environment:
            DOLTHUB_METRICS_ENABLED: "true"
            DOLTHUB_VERSION: "v2.2.1"
            EVENTSAPI_URL: "https://eventsapi.dolthub.com"
            INTERNAL_GRAPHQLAPI_URL: "http://doltlabenvoy:10080/graphql"
            IS_DOLTLAB_INSTANCE: "1"
            NODE_OPTIONS: "--max-old-space-size=16384"
            STRIPE_API_KEY: "does_not_work"
        networks:
            - default
networks:
    default:
        name: doltlab
        external: true
volumes:
    doltlab-remote-storage:
        name: doltlab_doltlab-remote-storage
    doltlab-user-uploads:
        name: doltlab_doltlab-user-uploads
    doltlabdb-dolt-backups:
        name: doltlab_doltlabdb-dolt-backups
    doltlabdb-dolt-configs:
        name: doltlab_doltlabdb-dolt-configs
    doltlabdb-dolt-data:
        name: doltlab_doltlabdb-dolt-data
    doltlabdb-dolt-root:
        name: doltlab_doltlabdb-dolt-root
```

**Comment by coffeegoddd** [comment]
@Podolyan98 Thanks for the info. It looks like this is a bug with DoltLab v2.2.1, which I was able to reproduce myself:
```bash
:/home/ubuntu/doltlab# docker logs doltlab-doltlabapi-1
2024-12-17T18:03:57.051Z	WARN	server/main.go:830	Generating random whitelist api token because none supplied in DOLTHUBAPI_WHITELIST_API_TOKEN.
main.getWhitelistTokenFromEnv
	go/services/dolthubapi/cmd/server/main.go:830
main.main
	go/services/dolthubapi/cmd/server/main.go:304
runtime.main
	GOROOT/src/runtime/proc.go:271
2024-12-17T18:04:03.187Z	INFO	server/main.go:953	Successfully created default user	{"default_user": "admin"}
2024-12-17T18:04:03.200Z	FATAL	server/main.go:401	Must supply -emailHost and -emailPort
main.main
	go/services/dolthubapi/cmd/server/main.go:401
runtime.main
	GOROOT/src/runtime/proc.go:271
```

The `installer` in this version is generating an invalid `docker-compose.yaml` which is causing the api to crash, cause it expects arguments that are not supplied. I'm going to update the release notes to recommend this release is not installed.

My recommendation is to do the following:
1. stop all DoltLab docker containers. `docker ps` should output no running containers.
2. run `docker system prune -a` to remove all docker containers and build cache.
3. use `docker volume ls` to list all docker volumes:
```bash
:/home/ubuntu/doltlab# docker volume ls
DRIVER    VOLUME NAME
local     doltlab_doltlab-remote-storage
local     doltlab_doltlab-user-uploads
local     doltlab_doltlabdb-dolt-backups
local     doltlab_doltlabdb-dolt-configs
local     doltlab_doltlabdb-dolt-data
local     doltlab_doltlabdb-dolt-root
```
and remove all of these with `docker volume rm <volume name>`. This will remove all DoltLab data persisted to disk.
4. remove the `doltlab` directory and the `doltlab-v2.2.1-zip` file.
5. download the latest DoltLab version, v2.3.4, with:
```bash
curl -LO https://doltlab-releases.s3.us-east-1.amazonaws.com/linux/amd64/doltlab-v2.3.4.zip
unzip doltlab-v2.3.4.zip -d doltlab
sudo newgrp docker
cd doltlab
```
6. edit `installer_config.yaml` to contain your host IP and your desired passwords. save the changes then run the `installer` binary.
```bash
:/home/ubuntu/doltlab# vim installer_config.yaml 
:/home/ubuntu/doltlab# ./installer 
2024-12-17T18:24:17.152Z	INFO	metrics/emitter.go:111	Successfully sent DoltLab usage metrics

2024-12-17T18:24:17.152Z	INFO	cmd/main.go:554	Successfully configured DoltLab	{"version": "v2.3.4"}

2024-12-17T18:24:17.152Z	INFO	cmd/main.go:560	To start DoltLab, use:	{"script": "/home/ubuntu/doltlab/start.sh"}
2024-12-17T18:24:17.152Z	INFO	cmd/main.go:565	To stop DoltLab, use:	{"script": "/home/ubuntu/doltlab/stop.sh"}
```
7. ensure ports `80`, `100`, `4321`, `50051` are all open on the host.
8. run `./start.sh`

You're instance should start and run correctly from there, I did this all myself this morning to confirm, but let me know if you hit any more snags.

**Comment by bpf120** [comment]
Hi @Podolyan98 , is DoltLab working now for you?

Also, we'd love to learn about your Dolt/DoltLab use case.  You can [email me](mailto:brianf@dolthub.com) or swing by our [Discord](https://discord.gg/gqr7K4VNKe) if you'd like to share.

**Comment by Podolyan98** [comment]
@coffeegoddd @bpf120 Dolt v2.3.4 works great. Thank you!
